services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Envoylope\NytrisPlugin\Amqp\Package\Initialiser:
        # Will be configured by PhpAmqpCompatExtension.
        public: true
